# Generated by Django 4.2.4 on 2023-09-06 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0002_quizresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='quiz_session',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='QuizApp.quiz'),
        ),
    ]
