# Generated by Django 4.2.4 on 2023-09-08 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0003_userresponse_quiz_session_alter_question_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='score',
            field=models.IntegerField(default=1),
        ),
    ]
